Add API client
cchangelabs/openepd pull request #3
Opened 2023-08-24 18:00 UTC by corvis

2023-08-28 10:11 UTC, alexlitvinenko requested changes

2023-08-28 10:11 UTC, alexlitvinenko commented on src/openepd/api/sync_client.py
> +
reformat `__all__`

2023-08-28 10:11 UTC, alexlitvinenko commented on src/openepd/model/epd.py
> +    valid_until: datetime.datetime | None = pyd.Field(
Describe datetime format.

2023-08-28 10:11 UTC, alexlitvinenko commented on src/openepd/model/pcr.py
> +        description="Jurisdiction(s) in which EPD is applicable. An empty array, or absent properties, "
Describe the format of a list item.

2023-08-28 13:15 UTC, irynadosiak-c-change-lab approved these changes

2023-08-30 14:19 UTC, alexche-cchange commented on src/openepd/api/epd/dto.py
> +    pct10_gwp: float = pyd.Field("10th percentile GWP for this statistics")
@alexlitvinenko I remember us recently having very same discussion about using floats for simple_baseline, and the conclusion was that everyone understands this is in kgCO2e, and we can safely use floats. 

Let's maybe just make it in comment - i.e. add `pyd.Field("10th percentile GWP for this statistics, in kg CO2 equivalent")`. 

Do you think that would be legit?

2023-08-30 14:20 UTC, alexlitvinenko commented on src/openepd/api/epd/dto.py
> +    pct10_gwp: float = pyd.Field("10th percentile GWP for this statistics")
Yes, that is what I meant. Just to describe in description.

2023-08-30 14:21 UTC, corvis commented on src/openepd/api/common.py
> +                self.goto_page(self.current_page + 1)
Goto page does nothing is target page == current page, just returns result as list

2023-08-30 17:41 UTC, corvis commented on src/openepd/api/epd/dto.py
> +    pct10_gwp: float = pyd.Field("10th percentile GWP for this statistics")
Updated description

2023-08-30 17:42 UTC, corvis commented on src/openepd/api/sync_client.py
> +    def epd(self) -> EpdApi:
done

2023-08-30 17:43 UTC, corvis commented on src/openepd/model/epd.py
>          description="Date the EPD was issued. This should be the first day on which the EPD is valid.",
It should be clear from the example (will be generated automatically during swager generation)

2023-08-30 17:46 UTC, corvis commented on src/openepd/model/pcr.py
> +        description="Jurisdiction(s) in which EPD is applicable. An empty array, or absent properties, "
done

2023-08-30 17:46 UTC, corvis commented on src/openepd/model/epd.py
> +    valid_until: datetime.datetime | None = pyd.Field(
see above

2023-08-30 17:48 UTC, corvis commented on src/openepd/api/base_sync_client.py
> +        return self.token == other.token
Done

2023-08-31 06:59 UTC, alexlitvinenko requested changes

2023-08-31 06:59 UTC, alexlitvinenko commented on src/openepd/api/errors.py
> +        self, http_status: int, error_summary: str, validation_errors: dict[str, list[str]] | None, response, error_code
type hint response and error_code

2023-08-31 06:59 UTC, alexlitvinenko commented on src/openepd/api/pcr/sync_api.py
> +        Get PCR by OpenEPD UUID.
```suggestion
        Get PCR by Open xPD UUID.
```

2023-08-31 06:59 UTC, alexlitvinenko commented on src/openepd/api/pcr/sync_api.py
> +        :param uuid: OpenEPD UUID
```suggestion
        :param uuid: Open xPD UUID
```

2023-08-31 06:59 UTC, alexlitvinenko commented on src/openepd/api/pcr/sync_api.py
> +        :return: EPD
```suggestion
        :return: PCR
```

2023-08-31 07:06 UTC, alexlitvinenko commented on src/openepd/model/pcr.py
> +    applicable_in: list[Annotated[str, pyd.Field(min_length=2, max_length=2)]] | None = pyd.Field(
EPD.applicable_in and PCR.applicable_in are accepting the same value:
The most recent description:
![image](https://github.com/cchangelabs/openepd/assets/5246563/fe0725b1-e04e-4bee-b1c7-a91bbad410cb)
https://github.com/cchangelabs/openepd-openapi/blob/dc720e754611b39961f0f1e2af50ec42b37d650d/content/schemas/models/EPD/Base.yaml#L143

2023-09-05 21:06 UTC, alexche-cchange approved these changes
looks good

2023-09-05 21:06 UTC, alexche-cchange commented on src/openepd/api/dto/common.py
> +class AuditableDto(BaseOpenEpdApiModel, metaclass=abc.ABCMeta):
Do you think we'll be able to replace the local version of same with this? E.g. the serverside.

2023-09-19 15:58 UTC, merged